services:
  - type: web
    name: the-outsider
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true 